/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Patrick
 */
public class dashboard_hoi extends javax.swing.JFrame {

    /**
     * Creates new form dashboard_hoi
     */
    public dashboard_hoi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbl_Bedrijfsnaam2 = new javax.swing.JLabel();
        lbl_Dashboard2 = new javax.swing.JLabel();
        lbl_Instellingen = new javax.swing.JLabel();
        lbl_Minimaliseren = new javax.swing.JLabel();
        lbl_Inloggen = new javax.swing.JLabel();
        lbl_Dash = new javax.swing.JLabel();
        lbl_Acties = new javax.swing.JLabel();
        lbl_Rapportage = new javax.swing.JLabel();
        lbl_Facturen = new javax.swing.JLabel();
        lbl_Opslag = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Datumtijd = new javax.swing.JLabel();
        lbl_Relaties = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_Acties1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lbl_Agenda = new javax.swing.JLabel();
        lbl_Rechten = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(1024, 768));

        lbl_Bedrijfsnaam2.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbl_Bedrijfsnaam2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Bedrijfsnaam2.setText("Cass B.V.");

        lbl_Dashboard2.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        lbl_Dashboard2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Dashboard2.setText("Dashboard => Karel Smits");

        lbl_Instellingen.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Settings_50px.png")); // NOI18N

        lbl_Minimaliseren.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Minimize Window_50px.png")); // NOI18N

        lbl_Inloggen.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Logout Rounded Up_50px.png")); // NOI18N

        lbl_Dash.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Dash.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Dash.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\View Carousel_25px.png")); // NOI18N
        lbl_Dash.setText("Dashboard");

        lbl_Acties.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Acties.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Acties.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\actie_25px.png")); // NOI18N
        lbl_Acties.setText("Acties");

        lbl_Rapportage.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Rapportage.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Rapportage.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Edit Graph Report_25px.png")); // NOI18N
        lbl_Rapportage.setText("Rapportage");

        lbl_Facturen.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Facturen.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Facturen.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Download From Cloud_25px.png")); // NOI18N
        lbl_Facturen.setText("Facturen");

        lbl_Opslag.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Opslag.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Opslag.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Opened Folder_25px.png")); // NOI18N
        lbl_Opslag.setText("Opslag");

        lbl_Email.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Email.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Email.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Important Mail_25px.png")); // NOI18N
        lbl_Email.setText("Email");

        lbl_Datumtijd.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Datumtijd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Datumtijd.setText("Datum : Tijd");

        lbl_Relaties.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Relaties.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Relaties.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Add User Group Man Man_25px.png")); // NOI18N
        lbl_Relaties.setText("Relaties");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("S:\\AO leerjaar 2\\stage_cass_bv\\netbeans\\image\\Search_25px.png")); // NOI18N
        jLabel1.setText("Search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_Bedrijfsnaam2)
                        .addGap(469, 469, 469)
                        .addComponent(lbl_Dashboard2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbl_Dash)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Relaties)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Rapportage)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Facturen)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Opslag)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Acties)
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Email)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_Datumtijd))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(484, 484, 484)
                        .addComponent(lbl_Instellingen)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_Minimaliseren)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Inloggen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Bedrijfsnaam2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Minimaliseren)
                    .addComponent(lbl_Inloggen)
                    .addComponent(lbl_Instellingen)
                    .addComponent(lbl_Dashboard2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Datumtijd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Dash, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Acties)
                        .addComponent(lbl_Rapportage, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Facturen)
                        .addComponent(lbl_Opslag)
                        .addComponent(lbl_Email)
                        .addComponent(lbl_Relaties, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbl_Acties1.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbl_Acties1.setText("AC");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lbl_Acties1)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_Acties1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );

        jPanel8.setPreferredSize(new java.awt.Dimension(440, 635));

        lbl_Agenda.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbl_Agenda.setText("Agenda");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lbl_Agenda)
                .addGap(125, 125, 125))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_Agenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Rechten.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lbl_Rechten.setText("All rights reserved Cass B.V.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Rechten)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(lbl_Rechten)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1935, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard_hoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard_hoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard_hoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard_hoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard_hoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_Acties;
    private javax.swing.JLabel lbl_Acties1;
    private javax.swing.JLabel lbl_Agenda;
    private javax.swing.JLabel lbl_Bedrijfsnaam2;
    private javax.swing.JLabel lbl_Dash;
    private javax.swing.JLabel lbl_Dashboard2;
    private javax.swing.JLabel lbl_Datumtijd;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Facturen;
    private javax.swing.JLabel lbl_Inloggen;
    private javax.swing.JLabel lbl_Instellingen;
    private javax.swing.JLabel lbl_Minimaliseren;
    private javax.swing.JLabel lbl_Opslag;
    private javax.swing.JLabel lbl_Rapportage;
    private javax.swing.JLabel lbl_Rechten;
    private javax.swing.JLabel lbl_Relaties;
    // End of variables declaration//GEN-END:variables
}
